### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by husimo** [kalvn/shaarli2mastodon#1]
Hello,
First of all, thank you for you plugin, that's really an easy way to publish to mastodon from shaarli.
I tried to publish a "note", not share a link. So as you can see the only the ID of my note is displayed on the toot : https://octodon.social/@husimo/98919611210256252
Is there a way to include the whole link ? 
And is there a possibility for a parameter which allow me to not display link to shaarli when it's a note and characters are <= 500 ?
Thank you, keep the good work :+1:

**Comment by kalvn** [comment]
Hi husimo and thanks for your feedback :)

You're right, by default, notes URL are not prefixed with the hostname, that's why you see this result. I'll fix that very soon.

The other point you mention is interesting. I guess I could create an additional placeholder which is only displayed when the description is too long. I'll think about it and let you know.

**Comment by kalvn** [comment]
Actually, the first point you mention should already be solved by this commit: https://github.com/kalvn/shaarli2mastodon/commit/1fa9eca94cd3ce42b56b6c99ecf6a5026423de8e

Did you get the very last version of the plugin?

**Comment by husimo** [comment]
Thank you and sorry for the delay of my answer.
Actually it seems that it's not solving the problem.
I cloned the repository today just before making a test.

**Comment by husimo** [comment]
Actually, using your commit, it's working. Thank you :)

**Comment by kalvn** [comment]
I'm glad to hear that :)
