### ISSUE TITLE
Support for Shaarli v.0.12

### ISSUE THREAD

**Issue by angristan** [kalvn/shaarli2mastodon#10]
Shaarli v0.12.0 has been released: https://github.com/shaarli/Shaarli/releases/tag/v0.12.0

Some changes seem to be required for plugins. I get this error:

```
shaarli2mastodon [plugin incompatibility]: Class 'Shaarli\Router' not found
```

Cheers!

**Comment by DansMonBulbe** [comment]
Have the same error but the plugin works correctly for me.

**Comment by solarchemist** [comment]
I got the exact same error message with the [latest shaarli2mastodon release (v2.0.0)](https://github.com/kalvn/shaarli2mastodon/releases/tag/v2.0.0).

But this appears to have been [fixed with the latest commit](https://github.com/kalvn/shaarli2mastodon/commit/50755237d0cd2196d73d2a30c0cf78a041f1ff1d). No error message anymore. Thanks @kalvn!

**Comment by angristan** [comment]
@solarchemist indeed, I didn't see that commit. I was using the latest release. Thanks!
